"""empty message

Revision ID: 94082dd1099b
Revises: dea41c344298
Create Date: 2023-03-26 15:23:34.350606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94082dd1099b'
down_revision = 'dea41c344298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_favs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'character_id')
    )
    op.create_table('episode_favs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'episode_id')
    )
    op.create_table('location_favs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'location_id')
    )
    op.drop_table('characters__locations')
    op.drop_table('episodes__characters')
    op.drop_table('favorites')
    op.drop_table('locations__episodes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations__episodes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('episode_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], name='locations__episodes_episode_id_fkey'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name='locations__episodes_location_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='locations__episodes_pkey')
    )
    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('episode_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='favorites_character_id_fkey'),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], name='favorites_episode_id_fkey'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name='favorites_location_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_pkey')
    )
    op.create_table('episodes__characters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('episode_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='episodes__characters_character_id_fkey'),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], name='episodes__characters_episode_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='episodes__characters_pkey')
    )
    op.create_table('characters__locations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='characters__locations_character_id_fkey'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name='characters__locations_location_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='characters__locations_pkey')
    )
    op.drop_table('location_favs')
    op.drop_table('episode_favs')
    op.drop_table('character_favs')
    # ### end Alembic commands ###
